### ISSUE TITLE
混淆

### ISSUE THREAD

**Issue by shingohu** [w446108264/XhsEmoticonsKeyboard#11]
混淆后表情不显示

**Comment by w446108264** [comment]
嗯，混淆问题可以根据如下解决

在demo中

1.使用了butterknife,所以需要在[proguard-rules.pro](https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/app/proguard-rules.pro)中加入
```java
-keep class butterknife.** { *; }
-dontwarn butterknife.internal.**
-keep class **$$ViewBinder { *; }

-keepclasseswithmembernames class * {
    @butterknife.* <fields>;
}

-keepclasseswithmembernames class * {
    @butterknife.* <methods>;
}
```



2.在[SimpleCommonUtils](https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/app/src/main/java/com/xhsemoticonskeyboard/common/SimpleCommonUtils.java)中，为了演示方便，使用了反射生成实例，
```java
 public static Object newInstance(Class _Class, int constructorIndex, Object... args) throws Exception {
        Constructor cons = _Class.getConstructors()[constructorIndex];
        return cons.newInstance(args);
 }
```
所以同样需要增加混淆设置，在[proguard-rules.pro](https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/app/proguard-rules.pro)中加入
```java
-keep class com.xhsemoticonskeyboard.common.adapter.emoticonadapter.** { *; }
-dontwarn com.xhsemoticonskeyboard.common.adapter.emoticonadapter.**
```



3.如果混淆的同时也配置了剔除无用资源文件，那么将会导致未声明的资源无法找到.
```groovy
minifyEnabled true
shrinkResources true
```
demo中，[reclib-qq](https://github.com/w446108264/XhsEmoticonsKeyboard/tree/master/XhsEmoticonsKeyboard/reclib-qq)的表情放置在[mipmap-xhdpi](https://github.com/w446108264/XhsEmoticonsKeyboard/tree/master/XhsEmoticonsKeyboard/reclib-qq/src/main/res/mipmap-xhdpi)中
[ImageLoader](https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/library/src/main/java/sj/keyboard/utils/imageloader/ImageLoader.java)获取资源文件是通过getIdentifier获取的，但由于shrinkResources true，这部分表情没有显式调用，编译后将会被剔除。导致资源文件无法找到。即shrinkResources导致getIdentifier获取资源失效

```java
 protected void displayImageFromDrawable(String imageUri, ImageView imageView) {
        String drawableIdString = Scheme.DRAWABLE.crop(imageUri);
        int resID = context.getResources().getIdentifier(drawableIdString, "mipmap", context.getPackageName());
        if (resID <= 0) {
            resID = context.getResources().getIdentifier(drawableIdString, "drawable", context.getPackageName());
        }
        if (resID > 0 && imageView != null) {
            imageView.setImageResource(resID);
        }
 }
```

所以我们需要增加剔除白名单[reclib-qq/src/main/rec/raw/keep.xml](https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/reclib-qq/src/main/res/raw/keep.xml)，把此类drawable或者mipmap的资源文件加入非剔除名单。

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="
    @mipmap/ecf,
    @mipmap/ecv,
    .../>
```


新的提交增加了混淆的演示

**Comment by w446108264** [comment]
已经支持int类型，支持直接设置Resource

**Comment by shingohu** [comment]
收到,谢谢
