### ISSUE TITLE
自定义布局中高度计算问题

### ISSUE THREAD

**Issue by edanel** [w446108264/XhsEmoticonsKeyboard#12]
在自定义AppsGirdView中页面下，点击切换到文本输入之后，再关闭键盘，AppsGirdView页面的高度被拉伸至与Emoticons页面高度一样

**Comment by w446108264** [comment]
是demo中的问题还是集成过程中遇到的问题？有截图吗？每次切换的view的高度都是可以单独指定的，取决于需求。

**Comment by edanel** [comment]
![1](http://7xaw0h.com1.z0.glb.clouddn.com/1.png)
![2](http://7xaw0h.com1.z0.glb.clouddn.com/2.png)
![3](http://7xaw0h.com1.z0.glb.clouddn.com/3.png)

只在第三方键盘中会出现这个问题。不过后面根据自己的需求已经修改好了。
感谢分享👍

**Comment by w446108264** [comment]
这的确是demo中的一个bug

如果有这样的需求，只需要在[userdef/SimpleUserdefEmoticonsKeyBoard.java](https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/app/src/main/java/com/xhsemoticonskeyboard/userdef/SimpleUserdefEmoticonsKeyBoard.java)中添加软键盘关闭的回调并手动调整高度即可

```java
@Override
public void OnSoftClose() {
        super.OnSoftClose();
        if (mLyKvml.getCurrentFuncKey() == FUNC_TYPE_APPPS) {
            setFuncViewHeight(EmoticonsKeyboardUtils.dip2px(getContext(), APPS_HEIGHT));
        }
 }
```

**Comment by w446108264** [comment]
@edanel

**Comment by edanel** [comment]
嗯，解决了。😎
