### ISSUE TITLE
发送出去的表情图片变了

### ISSUE THREAD

**Issue by yaojunyi3721** [w446108264/XhsEmoticonsKeyboard#13]
选择表情区域的一个表情 进入edittext还是那个样子 点击发送到了textivew中就变成同一个意思的另一个表情图片 或者说是另一套表情 因为每个表情区域的图片都有对应的另一个同样意思的图片
好像是使用了手机自带的表情了是吗 我不是很懂 但是这是不妥的 请问怎么解决

**Comment by w446108264** [comment]
有截图吗

**Comment by w446108264** [comment]
@yaojunyi3721

**Comment by yovenny** [comment]
将hashMap改成LinkedHashMap，hashMap是无序的。

**Comment by w446108264** [comment]
@yaojunyi3721 @yovenny 
非常感谢，检测issues的时候发现了这个问题，已经做了修复。
