### ISSUE TITLE
键盘失效

### ISSUE THREAD

**Issue by moyaying** [w446108264/XhsEmoticonsKeyboard#17]
activity设置android:configChanges="orientation|keyboardHidden|screenSize"后，旋转了方向后，出现各种bug。

**Comment by moyaying** [comment]
SoftKeyboardSizeWatchLayout.java              
  if (mScreenHeight == 0) {
                    mScreenHeight = r.bottom;
                }

当切换方向的时候，这里应该清零

**Comment by w446108264** [comment]
非常感谢，确实存在这样的问题。

compile 'com.github.w446108264:XhsEmoticonsKeyboard:2.0.4' 已经进行了修复

@moyaying
