### ISSUE TITLE
怎样隐藏输入框？

### ISSUE THREAD

**Issue by gnehsuy** [w446108264/XhsEmoticonsKeyboard#21]
怎样隐藏输入框？

**Comment by w446108264** [comment]
隐藏输入框？

**Comment by gnehsuy** [comment]
就是我在滑动ListView时，不想再看到输入框，当我点击评论时，就弹出输入框，类似微信朋友圈评论这种

**Comment by w446108264** [comment]
可以试试参考，简单自定义一个EmoticonsKeyBoard
https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/app/src/main/java/com/xhsemoticonskeyboard/userdef/SimpleUserdefEmoticonsKeyBoard.java

将输入框部分包裹在一个layout中，类似https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/app/src/main/res/layout/view_keyboard_qq.xml

然后在需要隐藏的地方，如onScrollStateChanged
setVisibility(View.GONE);
