### ISSUE TITLE
竖屏全屏bug

### ISSUE THREAD

**Issue by moyaying** [w446108264/XhsEmoticonsKeyboard#23]
竖屏全屏的时候，AutoHeightLayout不能达到最大高度，原因是onMeasure那里mConfigurationChangedFlag为false！

**Comment by w446108264** [comment]
竖屏全屏不能达到最大高度，是指部分机型如荣耀7，底部虚拟按键栏隐藏的时候？

可参考
https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/app/src/main/java/com/xhsemoticonskeyboard/activity/SimpleChatActivity.java

demo中的这个示例是全屏的。

**Comment by moyaying** [comment]
这个demo就是有问题，当ui显示后，我操作隐藏按键栏的时候，内容就会白一块。在加上旋转，会出现按键栏挡住键盘输入，不少问题！

**Comment by w446108264** [comment]
参考dev分支，已修复改问题
