### ISSUE TITLE
addEmoticonFilter 多个过滤器重复，导致只有后面的有效

### ISSUE THREAD

**Issue by 275873859** [w446108264/XhsEmoticonsKeyboard#24]
etContent.addEmoticonFilter(new EmojiFilter());
        etContent.addEmoticonFilter(new QqFilter());
两个都为自定义的，并且继承EmoticonFilter，但如果只单独使用一个，对于的表情没问题，但如果通过使用两个，则前面的过滤无效，显示 字符

**Comment by 275873859** [comment]
两个除了正则表达不一样，其他都一样，应该不影响吧
emoji的是Pattern.compile("[a-zA-Z0-9]+");
qq的是：Pattern.compile("\\[[a-zA-Z0-9\\u4e00-\\u9fa5]+\\]");
那个在前面，那个就无效

**Comment by w446108264** [comment]
💯这是一个好问题。
 
lib中对所有的EmoticonFilter都进行了遍历，无论之前是否成功。这是一个bug。
https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/library/src/main/java/sj/keyboard/widget/EmoticonsEditText.java
```java
    @Override
    protected final void onTextChanged(CharSequence arg0, int start, int lengthBefore, int after) {
        super.onTextChanged(arg0, start, lengthBefore, after);
        if(mFilterList == null){
            return;
        }
        for(EmoticonFilter emoticonFilter : mFilterList) {
            emoticonFilter.filter(this, arg0, start, lengthBefore, after);
        }
    }
```

不过demo中的emoji filter 可不是Pattern.compile("[a-zA-Z0-9]+");
而是，参考https://github.com/w446108264/AndroidEmoji

https://github.com/w446108264/AndroidEmoji/blob/master/AndroidEmoji/emoji/src/main/java/com/sj/emoji/EmojiDisplay.java
```java
  //                                                            0x203c,0x2049 0x20a0-0x32ff          0x1f00-0x1fff              0xfe4e5-0xfe4ee
    //                                                           |== !!, ?! ==||==== misc ====||======== emoticons ========||========= flags ==========|
    private static final Pattern EMOJI_RANGE = Pattern.compile("[\\u203c\\u2049\\u20a0-\\u32ff\\ud83c\\udc00-\\ud83d\\udeff\\udbb9\\udce5-\\udbb9\\udcee]");
```

可以看具体的示例。
https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/app/src/main/java/com/xhsemoticonskeyboard/common/SimpleCommonUtils.java
```java
 public static void initEmoticonsEditText(EmoticonsEditText etContent) {
        etContent.addEmoticonFilter(new EmojiFilter());
        etContent.addEmoticonFilter(new XhsFilter());
    }
```

另外EmoticonFilter是由开发者自由增加的，为了演示方便这里使用了多个filter，但在项目中完全可以根据需求合并为一个filter。

EmoticonFilter遍历的问题后续的版本会优化。

**Comment by 275873859** [comment]
谢谢，这是我们的emoji的 文本字符
            "1f60c", "1f60f", "1f61a", "1f61c",
            "1f61d", "1f62d", "1f601", "1f609",  所以，我也只能使用我的那个正则了
我将Filter合并再试试
