### ISSUE TITLE
添加表情问题

### ISSUE THREAD

**Issue by 275873859** [w446108264/XhsEmoticonsKeyboard#25]
如：QqUtils中：
`
      if(sCommonPageSetAdapter != null){
            return sCommonPageSetAdapter;
        }
        PageSetAdapter pageSetAdapter = new PageSetAdapter();

        addQqPageSetEntity(pageSetAdapter, context, emoticonClickListener);

        PageSetEntity pageSetEntity1 = new PageSetEntity.Builder()
                .addPageEntity(new PageEntity(new SimpleQqGridView(context)))
                .setIconUri(R.mipmap.dec)
                .setShowIndicator(false)
                .build();
        pageSetAdapter.add(pageSetEntity1);

        PageSetEntity pageSetEntity2 = new PageSetEntity.Builder()
                .addPageEntity(new PageEntity(new SimpleQqGridView(context)))
                .setIconUri(R.mipmap.mwi)
                .setShowIndicator(false)
                .build();
        pageSetAdapter.add(pageSetEntity2);

        return pageSetAdapter;`

一直在添加，而没有移除的操作，会不会一直内存占用？

**Comment by w446108264** [comment]
这部分是demo中的示例代码，不是lib的代码。开发可以根据自己的需求，从配置，或数据库选择相应加载方式。

原示例代码完整如下，为了演示方便，PageSetAdapter是static的，事实上只添加了一次，不会增加内存占用。

```java

public static PageSetAdapter sCommonPageSetAdapter;

public static PageSetAdapter getCommonAdapter(Context context, EmoticonClickListener emoticonClickListener) {

        if(sCommonPageSetAdapter != null){
            return sCommonPageSetAdapter;
        }

        PageSetAdapter pageSetAdapter = new PageSetAdapter();

        addEmojiPageSetEntity(pageSetAdapter, context, emoticonClickListener);

        addXhsPageSetEntity(pageSetAdapter, context, emoticonClickListener);

        addWechatPageSetEntity(pageSetAdapter, context, emoticonClickListener);

        addGoodGoodStudyPageSetEntity(pageSetAdapter, context, emoticonClickListener);

        addKaomojiPageSetEntity(pageSetAdapter, context, emoticonClickListener);

        addTestPageSetEntity(pageSetAdapter, context);

        return pageSetAdapter;
 }
```

**Comment by 275873859** [comment]
![Uploading QQ截图20160624161158.png…]()
正因为是static，所以，应该退出当前界面的时候，不会销毁，但我试了下，每次都要取执行后面的添加的操作

**Comment by w446108264** [comment]
demo中有很多的示例，不同的activity都有键盘，但他们的数据源大多是相同的，所以为了演示的方便，这里直接使用了static的Adapter。实际的开发中不推荐这样使用的。

**Comment by 275873859** [comment]
好吧，只能说我拿来主义习惯了  ^O^

**Comment by 275873859** [comment]
谢谢啦
