### ISSUE TITLE
comment keyboard问题

### ISSUE THREAD

**Issue by BusyHe** [w446108264/XhsEmoticonsKeyboard#27]
点击表情图标，怎么切换表情键盘和系统键盘？还有bottom_layout的高度

**Comment by w446108264** [comment]
参考https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/app/src/main/java/com/xhsemoticonskeyboard/activity/SimpleCommentActivity.java

**Comment by BusyHe** [comment]
好的，谢谢

**Comment by BusyHe** [comment]
额，我说的就是这个类，bottom_layout的高度你弄的是固定的，点击表情图标也是只显示表情键盘

**Comment by BusyHe** [comment]
？？是吗？

**Comment by w446108264** [comment]
SimpleCommentActivity.java 使用的键盘是EmoticonsKeyBoardPopWindow

**Comment by w446108264** [comment]
@BusyHe

**Comment by BusyHe** [comment]
![image](https://cloud.githubusercontent.com/assets/17348825/17470924/bd5c458e-5d72-11e6-8fb1-29cc4ae494db.png)
那这个view的高度我是不是得自己来写

**Comment by w446108264** [comment]
这个view只是demo示例的部分，和keyboard没有关系

**Comment by BusyHe** [comment]
是的，我的意思是，我想做类似这样像微博的布局，是不是自己写判断系统键盘的高度，然后还要点击其他的区域让EmoticonsKeyBoardPopWindow，显示和隐藏

**Comment by w446108264** [comment]
如果要实现微博的效果，那EmoticonsKeyBoardPopWindow是无法做到的，EmoticonsKeyBoardPopWindow主要针对简单的评论页面增加简单的表情键盘。实现微博效果可以参考https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/app/src/main/java/com/xhsemoticonskeyboard/qq/QqEmoticonsKeyBoard.java    QqEmoticonsKeyBoard qq表情键盘

**Comment by w446108264** [comment]
EmoticonsKeyBoardPopWindow是固定高度，不会考虑软键盘的变化

**Comment by w446108264** [comment]
简单修改样式的话，可以不必完全重写keyboard，继承XhsEmoticonsKeyboard，进行简单样式修改也可以满足需求，参考https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/app/src/main/java/com/xhsemoticonskeyboard/userdef/SimpleUserdefEmoticonsKeyBoard.java

**Comment by BusyHe** [comment]
嗯嗯，太谢谢了，我先看这两篇
