### ISSUE TITLE
求教，使用博主表情键盘时，得到的表情应该以何种方式上传

### ISSUE THREAD

**Issue by gaochunchun** [w446108264/XhsEmoticonsKeyboard#29]
抓包打印输出表情时，出现口口口等字符，求教若与服务器交互，应如何上传至服务器，服务器返回时，如何显示，感谢~

**Comment by w446108264** [comment]
是指emoji表情，还是自定义的表情，服务器的编码是什么？

**Comment by w446108264** [comment]
@gaochunchun

**Comment by gaochunchun** [comment]
emoji表情如何上传呢，这个好与服务器上的编码统一吗，博主的demo中是否有类似的参考代码可以参照，再次谢过。

**Comment by w446108264** [comment]
emoji表情不需要上传，服务器统一使用UTF-8就好，demo中没有可以参考的demo。抓包打印输出表情时，出现口口口等字符 因为emoji是unicode编码的，在android studio断点是可以看到表情的，但直接抓包，不保证你所用的软件支持改字符解析，所以出现了乱码。这不影响客户端的解析

**Comment by gaochunchun** [comment]
好的， 明白了 ， 多谢。
