### ISSUE TITLE
卡顿问题，出现频率较高

### ISSUE THREAD

**Issue by nvgtor** [w446108264/XhsEmoticonsKeyboard#30]
弹出键盘的时候输入框弹出卡顿，和隐藏键盘的时候，键盘能够快速隐藏但是键盘隐藏后输入框隐藏卡顿，以及输入框下面的屏幕是一片白底卡在那里，要等待一段时间才能隐藏。
在给出的 XhsEmoticonsKeyboard  demo中出现过一次，在我的项目中出现频率较高。我把卡顿的视频发到你的email了，还请帮忙看一看这个bug.

**Comment by w446108264** [comment]
有做耗时操作吗，关于自定义部分的源码发来看看

**Comment by w446108264** [comment]
@nvgtor

**Comment by nvgtor** [comment]
自定义 XhsEmoticonsKeyBoard 那部分逻辑上没有改变，只是去掉了录音按钮的UI，项目中有做耗时操作，这个确实是一个原因，因为卡顿的地方正是第一次打开聊天列表的时候，这个时候我有查询数据库的操作，可能影响了SoftKeyboardSizeWatchLayout中监听视图树的状态，导致软键盘的高度向下传递的时候出现了延迟。
另外，你的demo中，SimpleChatUserDefActivity里面，我也找到了有延时比较明显的地方，切换到大表情的时候，切换键盘就会出现延时，图的加载有延迟，
如下图：
![](https://raw.githubusercontent.com/nvgtor/res/b22addc1d98db6c2b5a390e218cc9e9c8d25085d/SimpleChatUserDefActivity.gif)

**Comment by w446108264** [comment]
动图大表情这里是为了简单演示，直接使用了glide加载gif，所以效果不是很好。卡顿的原因是gif的加载。

正确的做法是，一套动图表情集，每个表情包含静态预览图和动图原图，在表情面板显示静态预览图，发送显示动图原图。由于glide对gif的支持并不友好，所以glide结合https://github.com/koral--/android-gif-drawable  那么就能做到十分流畅了

**Comment by nvgtor** [comment]
恩，膜拜下，花了一个星期终于看懂了一些这个库的代码。佩服楼主对自定义View和事件处理这么熟练~~
