### ISSUE TITLE
qq表情问题

### ISSUE THREAD

**Issue by shucc** [w446108264/XhsEmoticonsKeyboard#31]
![image](https://cloud.githubusercontent.com/assets/9978185/17503638/01562924-5e24-11e6-947e-95090e996a4d.png)
请问下这些表情是从哪里获取的？reclib-qq中并未找到这些想过图片。

**Comment by w446108264** [comment]
这个是emoji表情 在参考https://github.com/w446108264/AndroidEmoji

**Comment by shucc** [comment]
好的，谢谢
