### ISSUE TITLE
demo "simple Chat Keyboard"有个bug

### ISSUE THREAD

**Issue by a1018875550** [w446108264/XhsEmoticonsKeyboard#36]
![3](https://cloud.githubusercontent.com/assets/8246218/19012549/e6b76b72-87eb-11e6-8f4f-3653a2c4e895.jpg)
如图，当我点击editeText输入时，就会这样；布局没有隐藏，顶在了输入法的上面

**Comment by w446108264** [comment]
什么机型呢？

是https://github.com/w446108264/XhsEmoticonsKeyboard/raw/master/output/simple.apk这个demo？还是在demo的基础上做了什么修改？

**Comment by a1018875550** [comment]
没有修改demo,只是修改了键盘的高度后就变成这样了，用的是魅蓝3

**Comment by w446108264** [comment]
确认这个问题是提交了开发版本的simple demo apk导致的。不会影响正常引入的lib使用。

已经上传了新的simple demo apk文件。
