### ISSUE TITLE
在Nexus6上布局乱掉了

### ISSUE THREAD

**Issue by loganguo** [w446108264/XhsEmoticonsKeyboard#40]
系统版本是6.0.1，用的是Nexus6。下载了APK安装后，选择“Simple Chat Keyboard”输入表情时布局乱掉了。
截图如下  
![2](https://cloud.githubusercontent.com/assets/9315399/19260873/d7e4b452-8fbf-11e6-8d35-37ebe4dc2bf5.png)
![1](https://cloud.githubusercontent.com/assets/9315399/19260875/dddedea0-8fbf-11e6-9389-b26d8c6b079f.png)

**Comment by w446108264** [comment]
确认这个问题是提交了开发版本的simple demo apk导致的。不会影响正常引入的lib使用。

已经上传了新的simple demo apk文件。
