### ISSUE TITLE
按下返回键时隐藏表情面板是如何设置的？

### ISSUE THREAD

**Issue by loganguo** [w446108264/XhsEmoticonsKeyboard#42]
看示例APK中都支持按下返回键，隐藏表情面板。只有在表情面板和键盘都隐藏的情况下，按下返回键才推出当前页面。试了下重写dispatchKeyEvent的方式和不做任何处理的方式，表现和示例都不一样，而是既隐藏表情面板又返回上一页。请问改如何设置呢？

**Comment by loganguo** [comment]
![image](https://cloud.githubusercontent.com/assets/9315399/19341037/606ad0c8-915e-11e6-833b-5094ae0382c7.png)
另外请问如何去掉如上图中的工具栏呢，我们自定义的图标比较少，一屏不满，下面的工具栏不让显示。

**Comment by w446108264** [comment]
1.需要注意结合EmoticonsEditText 并 处理该事件
https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/library/src/main/java/sj/keyboard/widget/EmoticonsEditText.java#91

```java

 @Override
    public boolean dispatchKeyEventPreIme(KeyEvent event) {
        if(onBackKeyClickListener != null){
            onBackKeyClickListener.onBackKeyClick();
        }
        return super.dispatchKeyEventPreIme(event);
    }

```




2.qq键盘是示例demo里面完全自定义的一个实现，也就是样式完全自定义，和核心lib无关，只是示例代码。所有你可以修改他所有的布局，如果不需要底部栏，直接在该View进行修改。
https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/app/src/main/java/com/xhsemoticonskeyboard/qq/QqEmoticonsKeyBoard.java

即修改该布局
https://github.com/w446108264/XhsEmoticonsKeyboard/blob/master/XhsEmoticonsKeyboard/app/src/main/res/layout/view_func_emoticon_qq.xml

**Comment by loganguo** [comment]
集成之后，当键盘弹出时会出现抖动的情况，不知道能否提供些排查的线索？
