### ISSUE TITLE
Simple APK Crash

### ISSUE THREAD

**Issue by dpyinjie** [w446108264/XhsEmoticonsKeyboard#8]
项目中的Simple APK安装直接crash，原因不明。

**Comment by w446108264** [comment]
安装失败？还是安装后打开crash？
什么机型呢

**Comment by dpyinjie** [comment]
Samsung A7, 安装成功的，打开就Crash了。

**Comment by w446108264** [comment]
连接IDE，提供crash log将有助于问题更好的解决

**Comment by izhijian** [comment]
红米2A 同样问题，安装成功，启动直接崩溃

**Comment by dpyinjie** [comment]
连接as调试，有没有Crash，这个simple.apk的问题。代码应该没问题！

**Comment by dpyinjie** [comment]
连接as调试，没有Crash，这个simple.apk的问题。代码应该没问题！
